# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-09 05:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_page_path', models.CharField(max_length=500)),
                ('page_path', models.CharField(max_length=500)),
                ('page_view_percent', models.DecimalField(decimal_places=15, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-15), django.core.validators.MaxValueValidator(100.0)])),
                ('page_views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='guessresult',
            unique_together=set([('previous_page_path', 'page_path')]),
        ),
    ]
